--- 
jobs: 
  test_pull_request: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v2
        with: 
          cache: npm
          node-version: 
            - 10.x
            - 12.x
            - 14.x
            - 15.x
      - 
        name: "Instaling Lerna"
        run: "npm install"
      - 
        name: "Install dependencies of the homemade packages."
        run: "npm run build:dev"
      - 
        name: Testing
        run: "npm run test"
name: CI
true: 
  pull_request: 
    branches: 
      - master
  push: 
    branches: 
      - master
  workflow_dispatch: ~
