name: Publish NPM packages

on:
  workflow_dispatch:
    inputs:
      version: 
        description: "Package version number"  

      # wix-velo/external-db-airtable:
      #   type: boolean
      #   description: "@wix-velo/external-db-airtable"
      #   default: true

      wix-velo/external-db-bigquery:
        type: boolean
        description: "@wix-velo/external-db-bigquery"
        default: true

      # wix-velo/external-db-config:
      #   type: boolean
      #   description: "@wix-velo/external-db-config"
      #   default: true

      wix-velo/external-db-dynamodb:
        type: boolean
        description: "@wix-velo/external-db-dynamodb"
        default: true

      # wix-velo/external-db-firestore:
      #   type: boolean
      #   description: "@wix-velo/external-db-firestore"
      #   default: true

      wix-velo/external-db-google-sheets:
        type: boolean
        description: "@wix-velo/external-db-google-sheets"
        default: true

      wix-velo/external-db-mongo:
        type: boolean
        description: "@wix-velo/external-db-mongo"
        default: true

      wix-velo/external-db-mssql:
        type: boolean
        description: "@wix-velo/external-db-mssql"
        default: true

      wix-velo/external-db-mysql:
        type: boolean
        description: "@wix-velo/external-db-mysql"
        default: true

      wix-velo/external-db-postgres:
        type: boolean
        description: "@wix-velo/external-db-postgres"
        default: true

      # wix-velo/external-db-security:
      #   type: boolean
      #   description: "@wix-velo/external-db-security"
      #   default: true

      wix-velo/external-db-spanner:
        type: boolean
        description: "@wix-velo/external-db-spanner"
        default: true

      # wix-velo/test-commons:
      #   type: boolean
      #   description: "@wix-velo/test-commons"
      #   default: true

      # wix-velo/velo-external-db-commons:
      #   type: boolean
      #   description: "@wix-velo/velo-external-db-commons"
      #   default: true

      wix-velo/velo-external-db-core:
        type: boolean
        description: "@wix-velo/velo-external-db-core"
        default: true

jobs:
  publish_npm_ackage:
  
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Installing NX
        run: npm install -g nx

      - run: npm install 

      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('.github/workflows/script.js')
            await script({github, context, core})
            


